version: "3"
services:
  redis:
    image: "cogn/redis:latest"
    container_name: cogn_redis
    build:
      context: ./redis
      dockerfile: Dockerfile

  mysql:
    image: "cogn/mysql:latest"
    container_name: cogn_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile

  php:
    image: "cogn/php:latest"
    container_name: cogn_php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app/src:/var/www/html
#    links:
#      - redis:redis
#      - mysql:mysql

  nginx:
    image: "cogn/nginx:latest"
    container_name: cogn_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./app/src:/var/www/html
#    links:
#      - php:php
